### ISSUE TITLE
SC - Can't get the caller address

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa-as-sdk#24] opened 2022-09-27 07:16 UTC
In our template : https://github.com/massalabs/massa-sc-template/blob/main/src/main.ts we call have three generate event. If we launch this in the testnet we have those events : 

```
command · get_filtered_sc_output_event operation_id=283ye1z7Tudk7ocqdWwjqt3cKSemENn44kMzsrw55x6zvEhtWa
Context: Slot: (period: 13882, thread: 6) at index: 0
On chain execution
Block id: KcUt2ABzJ6ViLSCHHkSJJKCvFnkTEkrV9PF8QbrRyqbFXjXsS
Origin operation id: 283ye1z7Tudk7ocqdWwjqt3cKSemENn44kMzsrw55x6zvEhtWa
Call stack: A1RDQQBKriCF7jXr9dDW65JCt346XCjYLd1KXv62nTtiuiy7P17

Data: Address = A123h4DyLbP6jx1eqBUuvP3myCCyBpJDWLVY9U4Sd5iuXdyJdtyZ

Context: Slot: (period: 13882, thread: 6) at index: 1
On chain execution
Block id: KcUt2ABzJ6ViLSCHHkSJJKCvFnkTEkrV9PF8QbrRyqbFXjXsS
Origin operation id: 283ye1z7Tudk7ocqdWwjqt3cKSemENn44kMzsrw55x6zvEhtWa
Call stack: A1RDQQBKriCF7jXr9dDW65JCt346XCjYLd1KXv62nTtiuiy7P17

Data: Hello, World!

Context: Slot: (period: 13882, thread: 6) at index: 2
On chain execution
Block id: KcUt2ABzJ6ViLSCHHkSJJKCvFnkTEkrV9PF8QbrRyqbFXjXsS
Origin operation id: 283ye1z7Tudk7ocqdWwjqt3cKSemENn44kMzsrw55x6zvEhtWa
Call stack: A1RDQQBKriCF7jXr9dDW65JCt346XCjYLd1KXv62nTtiuiy7P17

Data: 

? command › 
```

The third `generate_event` : `generateEvent(`${Context.caller().toByteString()}`)` doesn't print the address.

**Comment by AurelienFT** [comment] 2022-10-27 12:02
https://github.com/massalabs/massa-as-sdk/blob/main/assembly/std/context.ts#L46

**Comment by gregLibert** [comment] 2022-12-01 07:41
@Thykof can you test this and put it as a P1 if needed ?

**Comment by AurelienFT** [comment] 2022-12-01 08:17
@gregLibert @Thykof I saw people used `callee` to get the caller maybe it need more specification.

**Comment by Thykof** [comment] 2022-12-02 09:29
On testnet 17, I have reproduced the issue:

```typescript
import { generateEvent, Context } from "@massalabs/massa-as-sdk";

export function main(_args: StaticArray<u8>): StaticArray<u8> {
    generateEvent(`caller is ${Context.caller().toByteString()}`)
    generateEvent(`callee is ${Context.callee().toByteString()}`)
    return new StaticArray<u8>(0);
}
```

Output:

```
Deployment success with event: caller is
Deployment success with event: callee is A1hNwGrSXREPAPJVMFLDrkGEcKWEUPYtpUhg1pb7D9h6QBUqn2E
```

**Comment by gregLibert** [comment] 2022-12-08 19:18
The problem is here: https://github.com/massalabs/massa-as-sdk/blob/aa781b4ac2db12d19f63974b65f448fc88b03e97/assembly/std/context.ts#L56
For this specific situation where the callee and the caller are the same, we shouldn't returned a false empty address, but the same as the callee (the only address in the stack).

**Comment by Thykof** [comment] 2022-12-13 16:31
With #91 your suggestion @gregLibert is merged. So the output of my snippet above is now 

```
caller is A1qDAxGJ387ETi9JRQzZWSPKYq4YPXrFvdiE4VoXUaiAt38JFEC
callee is A1qDAxGJ387ETi9JRQzZWSPKYq4YPXrFvdiE4VoXUaiAt38JFEC
```

I think we can close this issue

**Closed** 2022-12-13 17:53 UTC
Labels: bug, good first issue, P3
